### ISSUE TITLE
Question:  Is this already released as a plugin?

### ISSUE THREAD

**Issue by ShravanSunder** [ozntel/oz-calendar#1]
Question:  Is this already released as a plugin?  I couldn't find it in the store.  @ozntel

**Comment by ozntel** [comment]
Not yet. The PR is pending at the moment: https://github.com/obsidianmd/obsidian-releases/pull/1748
Meanwhile, you can use the Obsidian BRAT plugin that helps you install plugins that are not currently available in the Community Plugins list.
