### ISSUE TITLE
Bug: Date format YYYYMMDDHHmmssSSS not work.

### ISSUE THREAD

**Issue by YIRU69** [ozntel/oz-calendar#2]
Hi, thanks for you making the plugin.
I try to select the yaml id with date format "YYYYMMDDHHmmssSSS". But it doesn't work. 
```
id: '20230416091914557'
```
![image](https://user-images.githubusercontent.com/48148292/232281256-7ed8456c-50de-45ed-b82c-17a7b413aeb0.png)

**Comment by ozntel** [comment]
The new release should solve the issue. Please let me know in case the issue persists after the update to `0.2.0` version

**Comment by YIRU69** [comment]
Thank you!
