### ISSUE TITLE
[Feature Request] Highlight today date

### ISSUE THREAD

**Issue by mvrai** [ozntel/oz-calendar#9]
It would be nice if the current day would be highlighted in color to distinguish it from the rest of the month.
Currently, the current day uses the style for the active day, so if you select any date, the selection from the current day disappears.

**Comment by ozntel** [comment]
Thanks for the suggestion. It is a good idea. This is now available in the new release. You can update from the community plugins. The current-day color can be adjusted using the Styles Settings plugin. Thanks!

**Comment by mvrai** [comment]
Much appreciated, looks great!
